"""empty message

Revision ID: 813a73752c59
Revises: 
Create Date: 2023-09-22 20:22:44.828658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813a73752c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Todo')
    # ### end Alembic commands ###
