version: '3.3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    expose:
      - '5000'
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'assessment'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
